name       : python-pkgconfig
version    : 1.5.5
release    : 7
source     :
    - https://pypi.io/packages/source/p/pkgconfig/pkgconfig-1.5.5.tar.gz : deb4163ef11f75b520d822d9505c1f462761b4309b1bb713d08689759ea8b899
license    : MIT
component  : programming.python
summary    : A Python interface to the pkg-config command line tool
description: |
    A Python interface to the pkg-config command line tool
build      : |
    %python3_setup
install    : |
    %python3_install
