name       : python-pkgconfig
version    : 1.5.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/6e/a9/ff67ef67217dfdf2aca847685fe789f82b931a6957a3deac861297585db6/pkgconfig-1.5.1.tar.gz : 97bfe3d981bab675d5ea3ef259045d7919c93897db7d3b59d4e8593cba8d354f
license    : MIT
component  : programming.python
summary    : A Python interface to the pkg-config command line tool
description: |
    A Python interface to the pkg-config command line tool
build      : |
    %python3_setup
install    : |
    %python3_install
