name       : python-pkgconfig
version    : 1.5.2
release    : 4
source     :
    - https://pypi.io/packages/source/p/pkgconfig/pkgconfig-1.5.2.tar.gz : 38d612488f0633755a2e7a8acab6c01d20d63dbc31af75e2a9ac98a6f638ca94
license    : MIT
component  : programming.python
summary    : A Python interface to the pkg-config command line tool
description: |
    A Python interface to the pkg-config command line tool
build      : |
    %python3_setup
install    : |
    %python3_install
